### ISSUE TITLE
이미지 사이즈 리사이즈 문제

### ISSUE THREAD

**Issue by kkh975** [kkh975/2210_image-picker#2]
## 배경
결국 이미지의 width x height 값 만큼 루프를 돌아야하기 때문에 이미지 리사이즈 필요.
(브라우저 위에 js의 경우 루프의 크기가 커질수록 급격하게 느려짐.)

## 문제
리사이즈시 정사이즈라면 문제가 되지 않지만,
비례가 맞지 않는 이미지일 경우 어떻게 처리해야할지 논의되어야 함.

아래 링크 확인하여 이미지 정책 지정해야 함.
(css의 이미지 처리 방식이지만, 이미지 policy는 아래 이외는 아직 없음)
참고: https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by htrucci** [comment]
@kkh975 서버에서 이미지 만들때 가로든 세로든 최대 500px 기준으로 리사이즈해서 드리면 되곘죠?

**Comment by kkh975** [comment]
@htrucci 어차피 클라이언트에서 다 제어가능해서 정책만 정하면 될듯함요.
사이즈는 500x500 정사이즈라고 정하면,
비율 안맞을시 어떻게 처리할지만 정하면 될듯해요~

컷할지 아니면 비는 공간을 white 처리할지 (위 링크 참고...)
