### ISSUE TITLE
포인트 갯수 인터랙션

### ISSUE THREAD

**Issue by htrucci** [kkh975/2210_image-picker#6]
@kkh975 

https://ibb.co/VmR1SFj

- [ ] 앱에서 포인트 갯수 설정하는거에 따라서 웹뷰에서 인터랙션이 되어야하는데요.

webView.evaluateJavaScript("setPointerCount(3);")  요런식으로 앱에서 스크립트 호출할거고

바뀐갯수에 따라 image.onload 안에 있는거 고대로 다시 실행하면 될 것 같거든요.

간단하게 제가 추가하려고 해도 타입스크립트는 어떻게해야할지 잘 모르겠네요 ㅋㅋ 

크롬 콘솔에서 타입스크립트 펑션 실행시키려면 대체 어떻게 해야하나요? 콘솔 호출이 되면 앱에서도 되는거라 생각하는데ㅋㅋ

도와주세요 슈파맨~

**Comment by kkh975** [comment]
@htrucci 
내용이 잘 이해가 안가요. 
통화주시죠 ㅎㅎㅎ

**Comment by kkh975** [comment]
구두로 처리되어 close 합니다.
